"use client";

import { motion } from "framer-motion";
import Container from "@/components/ui/Container";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import { EXTERNAL_LINKS } from "@/lib/constants";

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0 },
};

const roles = [
  {
    title: "Orchestrators",
    description:
      "GPU operators who perform video transcoding and AI processing work on the network. They stake LPT to signal reliability and compete for jobs based on price, performance, and uptime.",
    color: "border-green/50",
    icon: (
      <svg className="h-8 w-8" viewBox="0 0 32 32" fill="none">
        <rect x="6" y="6" width="20" height="20" rx="4" stroke="currentColor" strokeWidth="1.5" />
        <rect x="11" y="11" width="10" height="10" rx="2" stroke="currentColor" strokeWidth="1.5" fill="currentColor" fillOpacity="0.15" />
      </svg>
    ),
  },
  {
    title: "Gateways",
    description:
      "Entry points to the network that route video jobs to the best-suited orchestrators. They handle job selection, load balancing, and quality assurance on behalf of developers.",
    color: "border-white/20",
    icon: (
      <svg className="h-8 w-8" viewBox="0 0 32 32" fill="none">
        <circle cx="16" cy="8" r="4" stroke="currentColor" strokeWidth="1.5" />
        <circle cx="8" cy="24" r="4" stroke="currentColor" strokeWidth="1.5" />
        <circle cx="24" cy="24" r="4" stroke="currentColor" strokeWidth="1.5" />
        <path d="M16 12v4m-4 4l4-4 4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    title: "Delegators",
    description:
      "LPT holders who stake their tokens with orchestrators to help secure the network and earn a share of the fees and rewards generated by their chosen orchestrator.",
    color: "border-white/20",
    icon: (
      <svg className="h-8 w-8" viewBox="0 0 32 32" fill="none">
        <circle cx="16" cy="12" r="4" stroke="currentColor" strokeWidth="1.5" />
        <path d="M8 26c0-4.418 3.582-8 8-8s8 3.582 8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    title: "Developers",
    description:
      "Builders who integrate the Livepeer network into their applications through gateways. They send video processing jobs and receive transcoded or AI-processed output.",
    color: "border-white/20",
    icon: (
      <svg className="h-8 w-8" viewBox="0 0 32 32" fill="none">
        <path d="M12 10l-6 6 6 6M20 10l6 6-6 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
];

export default function NetworkPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative flex items-center overflow-hidden py-32 lg:py-40">
        <div
          className="pointer-events-none absolute inset-0"
          aria-hidden="true"
          style={{
            background:
              "radial-gradient(ellipse 60% 50% at 50% 40%, rgba(24,121,78,0.08) 0%, transparent 70%)",
          }}
        />
        <Container className="relative">
          <motion.div
            className="mx-auto max-w-3xl text-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
          >
            <p className="mb-3 font-mono text-sm font-medium tracking-wider text-green uppercase">
              The Network
            </p>
            <h1 className="text-4xl font-bold leading-tight tracking-tight sm:text-5xl lg:text-6xl">
              How Livepeer works
            </h1>
            <p className="mt-6 text-lg text-white/60">
              A decentralized network of GPU operators that performs video
              transcoding and AI video processing at scale, coordinated by the
              Livepeer protocol on Ethereum.
            </p>
          </motion.div>
        </Container>
      </section>

      {/* Architecture diagram */}
      <section className="border-t border-white/5 bg-dark-lighter py-24 lg:py-32">
        <Container>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            transition={{ staggerChildren: 0.15 }}
          >
            <motion.div variants={fadeUp} transition={{ duration: 0.5 }} className="text-center">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                Protocol architecture
              </h2>
              <p className="mx-auto mt-4 max-w-2xl text-lg text-white/60">
                Video flows through a layered architecture designed for
                reliability, performance, and cost efficiency.
              </p>
            </motion.div>

            <motion.div
              className="mx-auto mt-16 max-w-4xl"
              variants={fadeUp}
              transition={{ duration: 0.5 }}
            >
              <div className="flex flex-col items-center gap-4 md:flex-row md:gap-0">
                {[
                  {
                    step: "01",
                    label: "Application",
                    sub: "Sends video input via API",
                  },
                  {
                    step: "02",
                    label: "Gateway",
                    sub: "Routes to optimal orchestrators",
                  },
                  {
                    step: "03",
                    label: "Orchestrators",
                    sub: "GPU compute & AI processing",
                  },
                  {
                    step: "04",
                    label: "Verification",
                    sub: "On-chain proof of work",
                  },
                  {
                    step: "05",
                    label: "Output",
                    sub: "Transcoded or AI-processed video",
                  },
                ].map((item, i) => (
                  <div key={item.step} className="flex items-center">
                    <div
                      className={`flex flex-col items-center rounded-xl border ${
                        item.step === "03" ? "border-green/50" : "border-white/10"
                      } bg-dark px-5 py-5 text-center min-w-[140px]`}
                    >
                      <span className="font-mono text-xs text-green uppercase tracking-wider">
                        {item.step}
                      </span>
                      <span className="mt-1.5 text-sm font-medium">
                        {item.label}
                      </span>
                      <span className="mt-1 text-xs text-white/40">
                        {item.sub}
                      </span>
                    </div>
                    {i < 4 && (
                      <svg
                        className="mx-1 hidden h-4 w-6 flex-shrink-0 text-white/20 md:block"
                        viewBox="0 0 24 16"
                        fill="none"
                      >
                        <path
                          d="M0 8h20m0 0l-5-5m5 5l-5 5"
                          stroke="currentColor"
                          strokeWidth="1.5"
                        />
                      </svg>
                    )}
                  </div>
                ))}
              </div>
            </motion.div>
          </motion.div>
        </Container>
      </section>

      {/* Roles */}
      <section className="py-24 lg:py-32">
        <Container>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            transition={{ staggerChildren: 0.1 }}
          >
            <motion.div variants={fadeUp} transition={{ duration: 0.5 }} className="text-center">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                Network participants
              </h2>
              <p className="mx-auto mt-4 max-w-2xl text-lg text-white/60">
                Four key roles work together to power the Livepeer network.
              </p>
            </motion.div>

            <div className="mt-16 grid gap-6 sm:grid-cols-2">
              {roles.map((role) => (
                <motion.div key={role.title} variants={fadeUp} transition={{ duration: 0.5 }}>
                  <Card className={`h-full ${role.color}`}>
                    <div className="text-green">{role.icon}</div>
                    <h3 className="mt-4 text-lg font-medium">{role.title}</h3>
                    <p className="mt-2 text-sm leading-relaxed text-white/50">
                      {role.description}
                    </p>
                  </Card>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </Container>
      </section>

      {/* CTA */}
      <section className="border-t border-white/5 bg-dark-lighter py-24 lg:py-32">
        <Container>
          <motion.div
            className="mx-auto max-w-2xl text-center"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Explore the network
            </h2>
            <p className="mt-4 text-lg text-white/60">
              See orchestrators, staking data, and real-time network activity on
              the Livepeer Explorer.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Button href={EXTERNAL_LINKS.explorer} variant="primary">
                Open Explorer <span aria-hidden="true">&rarr;</span>
              </Button>
              <Button href={EXTERNAL_LINKS.docs} variant="secondary">
                Read the Docs
              </Button>
            </div>
          </motion.div>
        </Container>
      </section>
    </>
  );
}
