"use client";

import { motion } from "framer-motion";
import Container from "@/components/ui/Container";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import { EXTERNAL_LINKS } from "@/lib/constants";

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0 },
};

const tokenRoles = [
  {
    title: "Coordination",
    description:
      "LPT coordinates work on the network. Orchestrators stake LPT to signal capacity and reliability, creating a market for video processing services.",
    icon: (
      <svg className="h-8 w-8" viewBox="0 0 32 32" fill="none">
        <circle cx="16" cy="16" r="12" stroke="currentColor" strokeWidth="1.5" />
        <path d="M16 10v12M10 16h12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    title: "Security",
    description:
      "Staked LPT secures the network through economic incentives. Orchestrators are incentivized to perform honest work and can be penalized for misbehavior.",
    icon: (
      <svg className="h-8 w-8" viewBox="0 0 32 32" fill="none">
        <path
          d="M16 4l10 4v8c0 6-4.5 10.5-10 12-5.5-1.5-10-6-10-12V8l10-4z"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinejoin="round"
        />
      </svg>
    ),
  },
  {
    title: "Governance",
    description:
      "LPT holders participate in protocol governance, voting on proposals that shape the network's development and economic parameters.",
    icon: (
      <svg className="h-8 w-8" viewBox="0 0 32 32" fill="none">
        <path d="M6 26V14m10 12V6m10 20v-8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      </svg>
    ),
  },
];

const stakingSteps = [
  {
    step: "01",
    title: "Acquire LPT",
    description: "Get LPT from exchanges like Coinbase, Binance, or Uniswap.",
  },
  {
    step: "02",
    title: "Choose an Orchestrator",
    description:
      "Browse orchestrators on the Explorer and evaluate based on performance, fees, and reward share.",
  },
  {
    step: "03",
    title: "Delegate your LPT",
    description:
      "Stake your LPT with your chosen orchestrator to start earning rewards and fees.",
  },
  {
    step: "04",
    title: "Earn Rewards",
    description:
      "Receive your share of inflationary rewards and fees generated by your orchestrator's work.",
  },
];

export default function LPTPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative flex items-center overflow-hidden py-32 lg:py-40">
        <Container className="relative">
          <motion.div
            className="mx-auto max-w-3xl text-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
          >
            <p className="mb-3 font-mono text-sm font-medium tracking-wider text-white/40 uppercase">
              LPT Token
            </p>
            <h1 className="text-4xl font-bold leading-tight tracking-tight sm:text-5xl lg:text-7xl">
              The Livepeer token
            </h1>
            <p className="mt-6 text-lg text-white/60">
              LPT coordinates, secures, and governs the Livepeer network. Stake
              LPT to participate in the network and earn rewards.
            </p>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Button href={EXTERNAL_LINKS.staking} variant="primary">
                Stake LPT <span aria-hidden="true">&rarr;</span>
              </Button>
              <Button href={EXTERNAL_LINKS.explorer} variant="secondary">
                View Explorer
              </Button>
            </div>
          </motion.div>
        </Container>
      </section>

      {/* Token roles */}
      <section className="relative py-24 lg:py-32">
        <div className="divider-gradient absolute top-0 left-0 right-0" />
        <Container>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            transition={{ staggerChildren: 0.1 }}
          >
            <motion.div variants={fadeUp} transition={{ duration: 0.5 }} className="text-center">
              <h2 className="text-4xl font-bold tracking-tight sm:text-5xl">
                What LPT does
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-lg text-white/60">
                LPT is a work token that serves three essential functions in the
                Livepeer protocol.
              </p>
            </motion.div>

            <div className="mt-16 grid gap-6 md:grid-cols-3">
              {tokenRoles.map((role) => (
                <motion.div key={role.title} variants={fadeUp} transition={{ duration: 0.5 }}>
                  <Card className="h-full">
                    <div className="text-green">{role.icon}</div>
                    <h3 className="mt-4 text-lg font-medium">{role.title}</h3>
                    <p className="mt-2 text-sm leading-relaxed text-white/50">
                      {role.description}
                    </p>
                  </Card>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </Container>
      </section>

      {/* How to stake */}
      <section className="relative py-24 lg:py-32">
        <div className="divider-gradient absolute top-0 left-0 right-0" />
        <Container>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            transition={{ staggerChildren: 0.1 }}
          >
            <motion.div variants={fadeUp} transition={{ duration: 0.5 }} className="text-center">
              <h2 className="text-4xl font-bold tracking-tight sm:text-5xl">
                How to stake
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-lg text-white/60">
                Delegate your LPT to an orchestrator and start earning rewards
                in four steps.
              </p>
            </motion.div>

            <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {stakingSteps.map((item) => (
                <motion.div
                  key={item.step}
                  variants={fadeUp}
                  transition={{ duration: 0.5 }}
                  className="rounded-2xl border border-dark-border bg-dark-card p-6"
                >
                  <span className="font-mono text-2xl font-bold text-gradient">
                    {item.step}
                  </span>
                  <h3 className="mt-3 text-sm font-medium">{item.title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-white/50">
                    {item.description}
                  </p>
                </motion.div>
              ))}
            </div>

            <motion.div
              variants={fadeUp}
              transition={{ duration: 0.5 }}
              className="mt-12 text-center"
            >
              <Button href={EXTERNAL_LINKS.staking} variant="primary">
                Start Staking <span aria-hidden="true">&rarr;</span>
              </Button>
            </motion.div>
          </motion.div>
        </Container>
      </section>
    </>
  );
}
